version: "3.8"


services:
 neo4j:
   image: neo4j:5.12.0 # Use the latest stable version or specify your preferred version
   container_name: neo4j-server
   ports:
     - "7474:7474" # Browser UI
     - "7687:7687" # Bolt protocol for drivers and tools
   volumes:
     - neo4j_data:/data # Persistent data storage
     - neo4j_logs:/logs # Log storage
     - neo4j_import:/import # Import directory for CSV files
     - neo4j_plugins:/plugins # Plugin directory
   environment:
     - NEO4J_AUTH=neo4j/pwd1234567890 # username/password
     - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
     - NEO4J_dbms_connector_http_advertised__address=localhost:7474
   restart: unless-stopped


volumes:
 neo4j_data:
 neo4j_logs:
 neo4j_import:
 neo4j_plugins: